SELECT RETURNSTYPE_ID, 
       GRANDTOTAL, 
		 UPDATEDTIME,
		 STATUS,
		 ADD_NAME,
		 ADD_STATE,
		 ADD_PHONE1,
		 ADD_PHONE1,
		 PAY_NAME,
FROM ordreturns
WHERE USERSIDENTIFIER = 135652695
ORDER BY CREATEDTIME ASC;
