SELECT RETURNSTYPE_ID, 
       GRANDTOTAL, 
		 UPDATEDTIME,
		 STATUS,
		 ADD_NAME,
		 ADD_STATE,
		 ADD_PHONE1,
		 ADD_PHONE1,
		 PAY_NAME,
		 ADD_ADDRESS1,
		 PAY_EMAIL1,
		 COURIER_COUNTRY,
		 RESPONSE_TO_DATA
FROM ordreturns
WHERE USERSIDENTIFIER = 135652695
ORDER BY CREATEDTIME ASC;
